version: '3.8'

services:
  infomap:
    build:
      context: .
      dockerfile: Dockerfile
    image: schi11er/portfoliobim_infomap:latest
    container_name: infomap
    ports:
      - "1113:80"
    restart: unless-stopped
    environment:
      - REACT_APP_DATACAT_API_URL=${REACT_APP_DATACAT_API_URL}
      - REACT_APP_BACKEND_API_PORT=${REACT_APP_BACKEND_API_PORT}
